# Generated by Django 5.2.11 on 2026-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

    # ? py manage.py migrate komutu ile veritabanı tablolarını oluşturuyoruz. Bu komut, Django'nun varsayılan olarak kullandığı SQLite veritabanında gerekli tabloları oluşturur. Eğer farklı bir veritabanı kullanıyorsanız, DATABASES ayarlarını buna göre yapılandırmanız gerekir.
